# Generated by Django 4.2 on 2023-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('email_address', models.CharField(primary_key=True, serialize=False, verbose_name='person_user')),
                ('agency', models.CharField(max_length=25)),
                ('license_number', models.CharField(max_length=5)),
                ('commission_rate', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='property')),
                ('number_of_rooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'apartment',
            },
        ),
        migrations.CreateModel(
            name='apartment_location',
            fields=[
                ('apartment_location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_street_number', models.CharField(max_length=5)),
                ('street_street_name', models.CharField(max_length=20)),
                ('street_apt_number', models.CharField(max_length=5)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'apartment_location',
            },
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='property')),
                ('start_booking_date', models.DateField()),
                ('end_booking_date', models.DateField()),
                ('card_number', models.CharField(max_length=19, verbose_name='credit_card')),
                ('email_address', models.CharField(verbose_name='person_user')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='commercial_building',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='property')),
                ('square_footage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=200)),
                ('type_of_business', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'commercial_building',
            },
        ),
        migrations.CreateModel(
            name='commercial_building_location',
            fields=[
                ('commercial_building_location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_street_number', models.CharField(max_length=5)),
                ('street_street_name', models.CharField(max_length=20)),
                ('street_apt_number', models.CharField(max_length=5)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'commercial_building_location',
            },
        ),
        migrations.CreateModel(
            name='credit_card',
            fields=[
                ('email_address', models.CharField(verbose_name='person_user')),
                ('card_number', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('billing_address', models.CharField(max_length=35)),
                ('cardholder_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'credit_card',
            },
        ),
        migrations.CreateModel(
            name='email_address_telephone',
            fields=[
                ('email_address', models.CharField(primary_key=True, serialize=False, verbose_name='person_user')),
                ('telephone', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'email_address_telephone',
            },
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='property')),
                ('number_of_rooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='house_location',
            fields=[
                ('house_location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_street_number', models.CharField(max_length=5)),
                ('street_street_name', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'house_location',
            },
        ),
        migrations.CreateModel(
            name='person_user',
            fields=[
                ('email_address', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'person_user',
            },
        ),
        migrations.CreateModel(
            name='perspective_renter',
            fields=[
                ('email_address', models.CharField(primary_key=True, serialize=False, verbose_name='person_user')),
                ('desired_move_in_date', models.DateField()),
                ('preferred_location_city', models.CharField(max_length=20)),
                ('preferred_location_state', models.CharField(max_length=15)),
                ('budget', models.IntegerField()),
            ],
            options={
                'db_table': 'perspective_renter',
            },
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency', models.CharField(max_length=15)),
                ('location_address', models.CharField(max_length=20)),
                ('location_city', models.CharField(max_length=20)),
                ('location_state', models.CharField(max_length=15)),
                ('availability', models.DateField()),
                ('listing_type', models.CharField(max_length=10)),
                ('building_type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('email_address', models.CharField(default=None, primary_key=True, serialize=False, verbose_name='person_user')),
                ('street_street_number', models.CharField(max_length=5)),
                ('street_street_name', models.CharField(max_length=20)),
                ('street_apt_number', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('zip', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
